### ISSUE TITLE
Retry button not working with custom config

### ISSUE THREAD

**Issue by aliza-khu** [thegrizzlylabs/geniusscan-sdk-demo#87]
RNGeniusScan.scanWithConfiguration({
     source: 'camera',
     multiPage: false,
     defaultFilter: 'blackAndWhite',
     defaultFlashMode: 'auto',
})

Please refer to the below video:
https://github.com/thegrizzlylabs/geniusscan-sdk-demo/assets/112606371/5d570706-04c7-495d-a03e-bee635f419f3

Once tap on the retry button the camera closes and returns the below response:
{
  "multiPageDocumentUrl": "file:///var/mobile/Containers/Data/Application/-----/Documents/{filename}.pdf",
  "pdfURL": "file:///var/mobile/Containers/Data/Application/-----/Documents/{filename}.pdf",
  "scans": []
}

Expected: The user can able to retry and capture it again.

**Comment by guillaume-tgl** [comment]
We've just published a new version (5.1.0) that fixes this issue? Could you try it out?
See the changelog for more details: https://geniusscansdk.com/docs/changelog/

**Comment by aliza-khu** [comment]
@guillaume-tgl, After upgrading to version 5.1.0, I am still facing the same issue.

**Comment by aliza-khu** [comment]
@guillaume-tgl, The new update fixed this issue. Thank you. 🥳
